// Auto-generated by: python scripts/artisan2.py actions make-micsapi
// Do not edit manually.

import type * as t from "./types.gen";

export interface Paths {
  "/api/v1/accesorios": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        familia_id?: number[] | null;
        producto_id?: number[] | null;
        q?: string | null;
      };
      response: t.AccesorioListResponse;
    };
    post: {
      body: t.AccesorioCreate;
      response: unknown;
    };
  };
  "/api/v1/accesorios/search": {
    get: {
      query?: {
        query?: string;
        page?: number;
        page_size?: number;
      };
      response: t.AccesorioSearchResponse;
    };
  };
  "/api/v1/accesorios/{accesorio_id}": {
    get: {
      path: {
        accesorio_id: number;
      };
      response: t.AccesorioSingleResponse;
    };
    patch: {
      path: {
        accesorio_id: number;
      };
      body: t.AccesorioUpdate;
      response: t.AccesorioSingleResponse;
    };
    delete: {
      path: {
        accesorio_id: number;
      };
      response: t.AccesorioDeleteResponse;
    };
  };
  "/api/v1/admin/api-keys": {
    post: {
      body: t.ApiKeyAdminListRequest;
      response: t.ApiKeyRead[];
    };
  };
  "/api/v1/admin/api-keys/create": {
    post: {
      body: t.ApiKeyAdminCreateRequest;
      response: unknown;
    };
  };
  "/api/v1/api-keys": {
    get: {
      response: t.ApiKeyRead[];
    };
    post: {
      body: t.ApiKeyCreate;
      response: unknown;
    };
  };
  "/api/v1/api-keys/{api_key_id}": {
    delete: {
      path: {
        api_key_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/auditoria-respuestas/batch": {
    post: {
      body: t.AuditoriaRespuestasBatchInput;
      response: unknown;
    };
  };
  "/api/v1/auth/login": {
    post: {
      body: t.LoginRequestSchema;
      response: t.TokenResponseSchema;
    };
  };
  "/api/v1/auth/logout": {
    post: {
      response: unknown;
    };
  };
  "/api/v1/auth/me": {
    get: {
      response: t.UsuarioSchema;
    };
  };
  "/api/v1/auth/refresh": {
    post: {
      body: t.RefreshTokenRequest;
      response: t.TokenResponseSchema;
    };
  };
  "/api/v1/auth/register": {
    post: {
      body: t.UsuarioCreateSchema;
      response: t.UsuarioSchema;
    };
  };
  "/api/v1/bitacora-calidad": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        q?: string | null;
      };
      response: t.BitacoraCalidadListResponse;
    };
    post: {
      body: t.BitacoraCalidadCreate;
      response: unknown;
    };
  };
  "/api/v1/bitacora-calidad-actualizaciones": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        bitacora_id?: number | null;
      };
      response: t.BitacoraCalidadActualizacionListResponse;
    };
    post: {
      body: t.BitacoraCalidadActualizacionCreate;
      response: unknown;
    };
  };
  "/api/v1/bitacora-calidad-actualizaciones/{obj_id}": {
    get: {
      path: {
        obj_id: number;
      };
      response: t.BitacoraCalidadActualizacionSingleResponse;
    };
    patch: {
      path: {
        obj_id: number;
      };
      body: t.BitacoraCalidadActualizacionUpdate;
      response: t.BitacoraCalidadActualizacionSingleResponse;
    };
    delete: {
      path: {
        obj_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/bitacora-calidad-mejoras": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        bitacora_id?: number | null;
      };
      response: t.BitacoraCalidadMejoraListResponse;
    };
    post: {
      body: t.BitacoraCalidadMejoraCreate;
      response: unknown;
    };
  };
  "/api/v1/bitacora-calidad-mejoras/{obj_id}": {
    get: {
      path: {
        obj_id: number;
      };
      response: t.BitacoraCalidadMejoraSingleResponse;
    };
    patch: {
      path: {
        obj_id: number;
      };
      body: t.BitacoraCalidadMejoraUpdate;
      response: t.BitacoraCalidadMejoraSingleResponse;
    };
    delete: {
      path: {
        obj_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/bitacora-calidad/{obj_id}": {
    get: {
      path: {
        obj_id: number;
      };
      response: t.BitacoraCalidadSingleResponse;
    };
    patch: {
      path: {
        obj_id: number;
      };
      body: t.BitacoraCalidadUpdate;
      response: t.BitacoraCalidadSingleResponse;
    };
    delete: {
      path: {
        obj_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/bitacora-estatus": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
      };
      response: t.BitacoraEstatusListResponse;
    };
    post: {
      body: t.BitacoraEstatusCreate;
      response: unknown;
    };
  };
  "/api/v1/bitacora-estatus/{obj_id}": {
    get: {
      path: {
        obj_id: number;
      };
      response: t.BitacoraEstatusSingleResponse;
    };
    patch: {
      path: {
        obj_id: number;
      };
      body: t.BitacoraEstatusUpdate;
      response: t.BitacoraEstatusSingleResponse;
    };
    delete: {
      path: {
        obj_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/bodegas": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        centro_servicio_id?: number | null;
        q?: string | null;
      };
      response: t.BodegaListResponse;
    };
    post: {
      body: t.BodegaCreate;
      response: unknown;
    };
  };
  "/api/v1/bodegas/search": {
    get: {
      query?: {
        query?: string;
        page?: number;
        page_size?: number;
      };
      response: t.BodegaSearchResponse;
    };
  };
  "/api/v1/bodegas/{bodega_id}": {
    get: {
      path: {
        bodega_id: number;
      };
      response: t.BodegaSingleResponse;
    };
    patch: {
      path: {
        bodega_id: number;
      };
      body: t.BodegaUpdate;
      response: t.BodegaSingleResponse;
    };
    delete: {
      path: {
        bodega_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/causas": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        q?: string | null;
        familia_id?: number | null;
      };
      response: t.CausaListResponse;
    };
    post: {
      body: t.CausaCreate;
      response: unknown;
    };
  };
  "/api/v1/causas/search": {
    get: {
      query?: {
        query?: string;
        page?: number;
        page_size?: number;
      };
      response: t.CausaSearchResponse;
    };
  };
  "/api/v1/causas/{causa_id}": {
    get: {
      path: {
        causa_id: number;
      };
      response: t.CausaSingleResponse;
    };
    patch: {
      path: {
        causa_id: number;
      };
      body: t.CausaUpdate;
      response: t.CausaSingleResponse;
    };
    delete: {
      path: {
        causa_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/centros-de-servicio": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        q?: string | null;
      };
      response: t.CentroDeServicioListResponse;
    };
    post: {
      body: t.CentroDeServicioCreate;
      response: unknown;
    };
  };
  "/api/v1/centros-de-servicio/{centro_de_servicio_id}": {
    get: {
      path: {
        centro_de_servicio_id: number;
      };
      response: t.CentroDeServicioSingleResponse;
    };
    patch: {
      path: {
        centro_de_servicio_id: number;
      };
      body: t.CentroDeServicioUpdate;
      response: t.CentroDeServicioSingleResponse;
    };
    delete: {
      path: {
        centro_de_servicio_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/cliente-asesores": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        q?: string | null;
      };
      response: t.ClienteAsesorListResponse;
    };
    post: {
      body: t.ClienteAsesorCreate;
      response: unknown;
    };
  };
  "/api/v1/cliente-asesores/{obj_id}": {
    get: {
      path: {
        obj_id: number;
      };
      response: t.ClienteAsesorSingleResponse;
    };
    patch: {
      path: {
        obj_id: number;
      };
      body: t.ClienteAsesorUpdate;
      response: t.ClienteAsesorSingleResponse;
    };
    delete: {
      path: {
        obj_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/clientes": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        q?: string | null;
      };
      response: t.ClienteListResponse;
    };
    post: {
      body: t.ClienteCreate;
      response: unknown;
    };
  };
  "/api/v1/clientes/search": {
    get: {
      query?: {
        q?: string | null;
      };
      response: t.ClienteSearchResponse;
    };
  };
  "/api/v1/clientes/{cliente_id}": {
    get: {
      path: {
        cliente_id: number;
      };
      response: t.ClienteSingleResponse;
    };
    patch: {
      path: {
        cliente_id: number;
      };
      body: t.ClienteUpdate;
      response: t.ClienteSingleResponse;
    };
    delete: {
      path: {
        cliente_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/clientes/{cliente_id}/direcciones": {
    get: {
      path: {
        cliente_id: number;
      };
      query?: {
        skip?: number;
        limit?: number;
      };
      response: t.DireccionListResponse;
    };
    post: {
      path: {
        cliente_id: number;
      };
      body: t.DireccionCreate;
      response: unknown;
    };
  };
  "/api/v1/clientes/{cliente_id}/direcciones/{direccion_id}": {
    get: {
      path: {
        cliente_id: number;
        direccion_id: number;
      };
      response: t.DireccionSingleResponse;
    };
    patch: {
      path: {
        cliente_id: number;
        direccion_id: number;
      };
      body: t.DireccionUpdate;
      response: t.DireccionSingleResponse;
    };
    delete: {
      path: {
        cliente_id: number;
        direccion_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/configuracion-waterspider": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
      };
      response: t.ConfiguracionWaterspiderListResponse;
    };
    post: {
      body: t.ConfiguracionWaterspiderCreate;
      response: unknown;
    };
  };
  "/api/v1/configuracion-waterspider/by-centro/{centro_servicio_id}": {
    get: {
      path: {
        centro_servicio_id: number;
      };
      response: t.ConfiguracionWaterspiderSingleResponse;
    };
  };
  "/api/v1/configuracion-waterspider/{obj_id}": {
    get: {
      path: {
        obj_id: number;
      };
      response: t.ConfiguracionWaterspiderSingleResponse;
    };
    patch: {
      path: {
        obj_id: number;
      };
      body: t.ConfiguracionWaterspiderUpdate;
      response: t.ConfiguracionWaterspiderSingleResponse;
    };
    delete: {
      path: {
        obj_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/empresas": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        q?: string | null;
        activo?: boolean | null;
      };
      response: t.EmpresaListResponse;
    };
    post: {
      body: t.EmpresaCreate;
      response: unknown;
    };
  };
  "/api/v1/empresas/{empresa_id}": {
    get: {
      path: {
        empresa_id: number;
      };
      response: t.EmpresaSingleResponse;
    };
    patch: {
      path: {
        empresa_id: number;
      };
      body: t.EmpresaUpdate;
      response: t.EmpresaSingleResponse;
    };
    delete: {
      path: {
        empresa_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/fallas": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        producto_id?: number | null;
        q?: string | null;
      };
      response: t.FallaListResponse;
    };
    post: {
      body: t.FallaCreate;
      response: unknown;
    };
  };
  "/api/v1/fallas/search": {
    get: {
      query?: {
        query?: string;
        skip?: number;
        limit?: number;
      };
      response: t.FallaSearchResponse;
    };
  };
  "/api/v1/fallas/{falla_id}": {
    get: {
      path: {
        falla_id: number;
      };
      response: t.FallaSingleResponse;
    };
    patch: {
      path: {
        falla_id: number;
      };
      body: t.FallaUpdate;
      response: t.FallaSingleResponse;
    };
    delete: {
      path: {
        falla_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/familias-producto": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
      };
      response: t.FamiliaProductoListResponse;
    };
    post: {
      body: t.FamiliaProductoCreate;
      response: unknown;
    };
  };
  "/api/v1/familias-producto/abuelos": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
      };
      response: t.FamiliaProductoListResponse;
    };
  };
  "/api/v1/familias-producto/{familia_producto_id}": {
    get: {
      path: {
        familia_producto_id: number;
      };
      response: t.FamiliaProductoSingleResponse;
    };
    patch: {
      path: {
        familia_producto_id: number;
      };
      body: t.FamiliaProductoUpdate;
      response: t.FamiliaProductoSingleResponse;
    };
    delete: {
      path: {
        familia_producto_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/grupos-cola-fifo": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        centro_de_servicio_id?: number | null;
      };
      response: t.GruposColaFifoListResponse;
    };
    post: {
      body: t.GruposColaFifoCreate;
      response: unknown;
    };
  };
  "/api/v1/grupos-cola-fifo-familias/grupo/{grupo_id}": {
    get: {
      path: {
        grupo_id: number;
      };
      query?: {
        skip?: number;
        limit?: number;
      };
      response: t.GruposColaFifoFamiliasListResponse;
    };
  };
  "/api/v1/grupos-cola-fifo/{grupo_cola_fifo_id}": {
    get: {
      path: {
        grupo_cola_fifo_id: number;
      };
      response: t.GruposColaFifoSingleResponse;
    };
    put: {
      path: {
        grupo_cola_fifo_id: number;
      };
      body: t.GruposColaFifoUpdate;
      response: t.GruposColaFifoSingleResponse;
    };
    delete: {
      path: {
        grupo_cola_fifo_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/grupos-cola-fifo/{grupo_id}/familias": {
    get: {
      path: {
        grupo_id: number;
      };
      query?: {
        skip?: number;
        limit?: number;
      };
      response: t.GruposColaFifoFamiliasListResponse;
    };
    post: {
      path: {
        grupo_id: number;
      };
      body: t.GruposColaFifoFamiliasCreate;
      response: unknown;
    };
  };
  "/api/v1/grupos-cola-fifo/{grupo_id}/familias/{grupo_familia_id}": {
    delete: {
      path: {
        grupo_id: number;
        grupo_familia_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/guias": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        incidente_id?: number | null;
        estado?: string | null;
        centro_de_servicio_origen_id?: number | null;
        centro_de_servicio_destino_id?: number | null;
        q?: string | null;
      };
      response: t.GuiaListResponse;
    };
    post: {
      body: t.GuiaCreate;
      response: unknown;
    };
  };
  "/api/v1/guias/{guia_id}": {
    get: {
      path: {
        guia_id: number;
      };
      response: t.GuiaSingleResponse;
    };
    patch: {
      path: {
        guia_id: number;
      };
      body: t.GuiaUpdate;
      response: t.GuiaSingleResponse;
    };
    delete: {
      path: {
        guia_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/incidentes": {
    get: {
      query?: {
        codigo?: string | null;
        id?: number | null;
        observaciones?: string | null;
        estado?: t.EstadoIncidente[] | null;
        cola_de_reparacion?: boolean;
        q?: string | null;
        skip?: number;
        limit?: number;
      };
      response: t.IncidenteListResponse;
    };
    post: {
      body: t.IncidenteCreate;
      response: unknown;
    };
  };
  "/api/v1/incidentes/ingreso-completo": {
    post: {
      body: t.IngresoCompletoInput;
      response: unknown;
    };
  };
  "/api/v1/incidentes/mis-asignaciones": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
      };
      response: t.IncidenteListResponse;
    };
  };
  "/api/v1/incidentes/search": {
    get: {
      query?: {
        q?: string | null;
      };
      response: t.IncidenteListResponse;
    };
  };
  "/api/v1/incidentes/{incidente_id}": {
    get: {
      path: {
        incidente_id: number;
      };
      response: t.IncidenteSingleResponse;
    };
    patch: {
      path: {
        incidente_id: number;
      };
      body: t.IncidenteUpdate;
      response: t.IncidenteSingleResponse;
    };
    delete: {
      path: {
        incidente_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/incidentes/{incidente_id}/asignados": {
    post: {
      path: {
        incidente_id: number;
      };
      body: t.AsignarUsuarioSchema;
      response: t.IncidenteSingleResponse;
    };
  };
  "/api/v1/incidentes/{incidente_id}/asignados/{user_id}": {
    delete: {
      path: {
        incidente_id: number;
        user_id: number;
      };
      response: t.IncidenteSingleResponse;
    };
  };
  "/api/v1/incidentes/{incidente_id}/cambiar-estado": {
    post: {
      path: {
        incidente_id: number;
      };
      body: t.IncidenteCambiarEstadoInput;
      response: t.IncidenteSingleResponse;
    };
  };
  "/api/v1/incidentes/{incidente_id}/diagnosticos": {
    get: {
      path: {
        incidente_id: number;
      };
      query?: {
        estado?: t.EstadoDiagnostico | null;
        skip?: number;
        limit?: number;
      };
      response: t.DiagnosticoListResponse;
    };
    post: {
      path: {
        incidente_id: number;
      };
      body: t.DiagnosticoCreateInput;
      response: unknown;
    };
  };
  "/api/v1/incidentes/{incidente_id}/diagnosticos/draft": {
    get: {
      path: {
        incidente_id: number;
      };
      response: t.DiagnosticoSingleResponse;
    };
    post: {
      path: {
        incidente_id: number;
      };
      body: t.DiagnosticoCreateInput;
      response: unknown;
    };
  };
  "/api/v1/incidentes/{incidente_id}/participaciones": {
    get: {
      path: {
        incidente_id: number;
      };
      query?: {
        skip?: number;
        limit?: number;
      };
      response: t.IncidenteParticipacionListResponse;
    };
  };
  "/api/v1/inventario": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        centro_servicio_id?: number | null;
        ubicacion_id?: number | null;
      };
      response: t.InventarioRead[];
    };
    post: {
      body: t.InventarioCreate;
      response: unknown;
    };
  };
  "/api/v1/inventario-repuestos": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        q?: string | null;
      };
      response: t.InventarioRepuestoListResponse;
    };
    post: {
      body: t.InventarioRepuestoCreate;
      response: unknown;
    };
  };
  "/api/v1/inventario-repuestos/{inventario_repuesto_id}": {
    get: {
      path: {
        inventario_repuesto_id: number;
      };
      response: t.InventarioRepuestoSingleResponse;
    };
    patch: {
      path: {
        inventario_repuesto_id: number;
      };
      body: t.InventarioRepuestoUpdate;
      response: t.InventarioRepuestoSingleResponse;
    };
    delete: {
      path: {
        inventario_repuesto_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/inventario/{inventario_id}": {
    get: {
      path: {
        inventario_id: number;
      };
      response: t.InventarioRead;
    };
    put: {
      path: {
        inventario_id: number;
      };
      body: t.InventarioUpdate;
      response: t.InventarioRead;
    };
    delete: {
      path: {
        inventario_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/movimientos-inventario": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        centro_servicio_id?: number | null;
        repuesto_id?: number | null;
        tipo_movimiento?: t.TipoMovimientoInventario | null;
      };
      response: t.MovimientoInventarioListResponse;
    };
    post: {
      body: t.MovimientoInventarioCreate;
      response: unknown;
    };
  };
  "/api/v1/movimientos-inventario/{movimiento_id}": {
    get: {
      path: {
        movimiento_id: number;
      };
      response: t.MovimientoInventarioSingleResponse;
    };
    delete: {
      path: {
        movimiento_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/notificaciones/notificaciones/usuario/{user_id}": {
    get: {
      path: {
        user_id: number;
      };
      response: t.NotificacionRead[];
    };
    post: {
      path: {
        user_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/paginas": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        q?: string | null;
      };
      response: t.PaginaListResponse;
    };
    post: {
      body: t.PaginaCreate;
      response: unknown;
    };
  };
  "/api/v1/paginas/{obj_id}": {
    get: {
      path: {
        obj_id: number;
      };
      response: t.PaginaSingleResponse;
    };
    patch: {
      path: {
        obj_id: number;
      };
      body: t.PaginaUpdate;
      response: t.PaginaSingleResponse;
    };
    delete: {
      path: {
        obj_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/picking-log": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        item_id?: number | null;
      };
      response: t.ListadoAbastecimientoPickingLogListResponse;
    };
    post: {
      body: t.ListadoAbastecimientoPickingLogCreate;
      response: unknown;
    };
  };
  "/api/v1/picking-log/{obj_id}": {
    get: {
      path: {
        obj_id: number;
      };
      response: t.ListadoAbastecimientoPickingLogSingleResponse;
    };
    patch: {
      path: {
        obj_id: number;
      };
      body: t.ListadoAbastecimientoPickingLogUpdate;
      response: t.ListadoAbastecimientoPickingLogSingleResponse;
    };
    delete: {
      path: {
        obj_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/preguntas-auditoria": {
    get: {
      query?: {
        seccion?: string | null;
        activo?: boolean | null;
        skip?: number;
        limit?: number;
      };
      response: t.PreguntaAuditoriaListResponse;
    };
    post: {
      body: t.PreguntaAuditoriaCreate;
      response: unknown;
    };
  };
  "/api/v1/preguntas-auditoria/{pregunta_auditoria_id}": {
    get: {
      path: {
        pregunta_auditoria_id: number;
      };
      response: t.PreguntaAuditoriaSingleResponse;
    };
    patch: {
      path: {
        pregunta_auditoria_id: number;
      };
      body: t.PreguntaAuditoriaUpdate;
      response: t.PreguntaAuditoriaSingleResponse;
    };
    delete: {
      path: {
        pregunta_auditoria_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/productos": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        q?: string | null;
      };
      response: t.ProductoListResponse;
    };
    post: {
      body: t.ProductoCreate;
      response: unknown;
    };
  };
  "/api/v1/productos/search": {
    get: {
      query?: {
        q?: string | null;
      };
      response: t.ProductoSearchResponse;
    };
  };
  "/api/v1/productos/{producto_id}": {
    get: {
      path: {
        producto_id: number;
      };
      response: t.ProductoSingleResponse;
    };
    patch: {
      path: {
        producto_id: number;
      };
      body: t.ProductoUpdate;
      response: t.ProductoSingleResponse;
    };
    delete: {
      path: {
        producto_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/repuestos": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        q?: string | null;
        familia_id?: number | null;
      };
      response: t.RepuestoListResponse;
    };
    post: {
      body: t.RepuestoCreate;
      response: unknown;
    };
  };
  "/api/v1/repuestos/{repuesto_id}": {
    get: {
      path: {
        repuesto_id: number;
      };
      response: t.RepuestoSingleResponse;
    };
    patch: {
      path: {
        repuesto_id: number;
      };
      body: t.RepuestoUpdate;
      response: t.RepuestoSingleResponse;
    };
    delete: {
      path: {
        repuesto_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/rol-paginas": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        rol_id?: number | null;
      };
      response: t.RolPaginaListResponse;
    };
    post: {
      body: t.RolPaginaCreate;
      response: unknown;
    };
  };
  "/api/v1/rol-paginas/{obj_id}": {
    get: {
      path: {
        obj_id: number;
      };
      response: t.RolPaginaSingleResponse;
    };
    patch: {
      path: {
        obj_id: number;
      };
      body: t.RolPaginaUpdate;
      response: t.RolPaginaSingleResponse;
    };
    delete: {
      path: {
        obj_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/roles/": {
    get: {
      response: t.RolListResponse;
    };
  };
  "/api/v1/tipologias": {
    get: {
      response: unknown;
    };
  };
  "/api/v1/ubicaciones": {
    get: {
      query?: {
        skip?: number;
        limit?: number;
        bodega_id?: number | null;
        q?: string | null;
      };
      response: t.UbicacionListResponse;
    };
    post: {
      body: t.UbicacionCreate;
      response: unknown;
    };
  };
  "/api/v1/ubicaciones/{ubicacion_id}": {
    get: {
      path: {
        ubicacion_id: number;
      };
      response: t.UbicacionSingleResponse;
    };
    patch: {
      path: {
        ubicacion_id: number;
      };
      body: t.UbicacionUpdate;
      response: t.UbicacionSingleResponse;
    };
    delete: {
      path: {
        ubicacion_id: number;
      };
      response: unknown;
    };
  };
  "/api/v1/usuarios/": {
    get: {
      response: t.UsuarioReadWithRoles[];
    };
  };
  "/api/v1/verificaciones-reincidencia": {
    get: {
      query?: {
        incidente_id?: number | null;
        verificado?: boolean | null;
        skip?: number;
        limit?: number;
      };
      response: t.VerificacionReincidenciaListResponse;
    };
    post: {
      body: t.VerificacionReincidenciaCreate;
      response: unknown;
    };
  };
  "/api/v1/verificaciones-reincidencia/{verificacion_id}": {
    get: {
      path: {
        verificacion_id: number;
      };
      response: t.VerificacionReincidenciaSingleResponse;
    };
    patch: {
      path: {
        verificacion_id: number;
      };
      body: t.VerificacionReincidenciaUpdate;
      response: t.VerificacionReincidenciaSingleResponse;
    };
    delete: {
      path: {
        verificacion_id: number;
      };
      response: unknown;
    };
  };
}

// Utility types
export type PathsWithMethod<M extends string> = {
  [P in keyof Paths]: M extends keyof Paths[P] ? P : never;
}[keyof Paths];
