// Auto-generated by: python scripts/artisan2.py actions make-micsapi
// Do not edit manually.

export interface AccesorioCreate {
  nombre: string;
  descripcion?: string | null;
  familia_id?: number | null;
}

export interface AccesorioDeleteResponse {
  message?: string;
}

export interface AccesorioListResponse {
  results: AccesorioRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface AccesorioRead {
  nombre: string;
  descripcion?: string | null;
  familia_id?: number | null;
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export interface AccesorioSearchResponse {
  results: AccesorioRead[];
  total: number;
}

export interface AccesorioSingleResponse {
  result: AccesorioRead;
}

export interface AccesorioUpdate {
  nombre?: string | null;
  descripcion?: string | null;
  familia_id?: number | null;
}

export interface ApiKeyAdminCreateRequest {
  email: string;
  name: string;
}

export interface ApiKeyAdminListRequest {
  email: string;
}

export interface ApiKeyCreate {
  name: string;
}

export interface ApiKeyCreatedResponse {
  name: string;
  is_active?: boolean;
  expires_at?: string | null;
  last_used_at?: string | null;
  id: number;
  user_id: number;
  key_hash: string;
  created_at: string;
  raw_key: string;
}

export interface ApiKeyRead {
  name: string;
  is_active?: boolean;
  expires_at?: string | null;
  last_used_at?: string | null;
  id: number;
  user_id: number;
  key_hash: string;
  created_at: string;
}

export interface AsignarUsuarioSchema {
  user_id: number;
}

export interface AuditoriaRespuestaCreate {
  pregunta_auditoria_id: number;
  respuesta: boolean;
  observaciones?: string | null;
}

export interface AuditoriaRespuestaRead {
  pregunta_auditoria_id: number;
  respuesta: boolean;
  observaciones?: string | null;
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export interface AuditoriaRespuestasBatchInput {
  respuestas: AuditoriaRespuestaCreate[];
}

export interface AuditoriaRespuestasBatchOutput {
  results: AuditoriaRespuestaRead[];
}

export interface BitacoraCalidadActualizacionCreate {
  bitacora_id: number;
  numero_actualizacion: number;
  contenido: string;
  fecha_actualizacion?: string | null;
  responsable_id?: number | null;
  semana?: number | null;
  anio?: number | null;
  mejora_id?: number | null;
}

export interface BitacoraCalidadActualizacionListResponse {
  results: BitacoraCalidadActualizacionRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface BitacoraCalidadActualizacionRead {
  bitacora_id: number;
  numero_actualizacion: number;
  contenido: string;
  fecha_actualizacion?: string | null;
  responsable_id?: number | null;
  semana?: number | null;
  anio?: number | null;
  mejora_id?: number | null;
  id: number;
  created_at?: string | null;
}

export interface BitacoraCalidadActualizacionSingleResponse {
  result: BitacoraCalidadActualizacionRead;
}

export interface BitacoraCalidadActualizacionUpdate {
  numero_actualizacion?: number | null;
  contenido?: string | null;
  fecha_actualizacion?: string | null;
  responsable_id?: number | null;
  semana?: number | null;
  anio?: number | null;
  mejora_id?: number | null;
}

export interface BitacoraCalidadCreate {
  origen?: string | null;
  clave?: string | null;
  codigo?: string | null;
  descripcion_codigo?: string | null;
  problema?: string | null;
  incidencia_porcentaje?: number | string | null;
  mejora?: string | null;
  fecha_entregable?: string | null;
  responsable_id?: number | null;
  estatus_id?: number | null;
  created_by?: number | null;
  responsable_nombre?: string | null;
}

export interface BitacoraCalidadListResponse {
  results: BitacoraCalidadRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface BitacoraCalidadMejoraCreate {
  bitacora_id: number;
  numero_mejora: number;
  descripcion: string;
  fecha_registro?: string | null;
  responsable_nombre?: string | null;
}

export interface BitacoraCalidadMejoraListResponse {
  results: BitacoraCalidadMejoraRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface BitacoraCalidadMejoraRead {
  bitacora_id: number;
  numero_mejora: number;
  descripcion: string;
  fecha_registro?: string | null;
  responsable_nombre?: string | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface BitacoraCalidadMejoraSingleResponse {
  result: BitacoraCalidadMejoraRead;
}

export interface BitacoraCalidadMejoraUpdate {
  numero_mejora?: number | null;
  descripcion?: string | null;
  fecha_registro?: string | null;
  responsable_nombre?: string | null;
}

export interface BitacoraCalidadRead {
  origen?: string | null;
  clave?: string | null;
  codigo?: string | null;
  descripcion_codigo?: string | null;
  problema?: string | null;
  incidencia_porcentaje?: string | null;
  mejora?: string | null;
  fecha_entregable?: string | null;
  responsable_id?: number | null;
  estatus_id?: number | null;
  created_by?: number | null;
  responsable_nombre?: string | null;
  id: number;
  fecha_registro?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface BitacoraCalidadSingleResponse {
  result: BitacoraCalidadRead;
}

export interface BitacoraCalidadUpdate {
  origen?: string | null;
  clave?: string | null;
  codigo?: string | null;
  descripcion_codigo?: string | null;
  problema?: string | null;
  incidencia_porcentaje?: number | string | null;
  mejora?: string | null;
  fecha_entregable?: string | null;
  responsable_id?: number | null;
  estatus_id?: number | null;
  responsable_nombre?: string | null;
}

export interface BitacoraEstatusCreate {
  nombre: string;
  color?: string;
  orden?: number;
  activo?: boolean;
  es_final?: boolean;
  responsable_fase?: string | null;
}

export interface BitacoraEstatusListResponse {
  results: BitacoraEstatusRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface BitacoraEstatusRead {
  nombre: string;
  color?: string;
  orden?: number;
  activo?: boolean;
  es_final?: boolean;
  responsable_fase?: string | null;
  id: number;
  created_at: string;
}

export interface BitacoraEstatusSingleResponse {
  result: BitacoraEstatusRead;
}

export interface BitacoraEstatusUpdate {
  nombre?: string | null;
  color?: string | null;
  orden?: number | null;
  activo?: boolean | null;
  es_final?: boolean | null;
  responsable_fase?: string | null;
}

export interface BodegaCreate {
  uuid_id: string;
  nombre?: string | null;
  codigo?: string | null;
  centro_servicio_id?: number | null;
  activo: boolean;
}

export interface BodegaListResponse {
  results: BodegaRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface BodegaRead {
  uuid_id: string;
  nombre?: string | null;
  codigo?: string | null;
  centro_servicio_id?: number | null;
  activo: boolean;
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export interface BodegaSearchResponse {
  results: BodegaRead[];
  total: number;
}

export interface BodegaSingleResponse {
  result: BodegaRead;
}

export interface BodegaUpdate {
  uuid_id?: string | null;
  nombre?: string | null;
  codigo?: string | null;
  centro_servicio_id?: number | null;
  activo?: boolean | null;
}

export interface CausaCreate {
  nombre: string;
  familia_id?: number | null;
}

export interface CausaListResponse {
  results: CausaRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface CausaNested {
  id: number;
  nombre: string;
}

export interface CausaRead {
  nombre: string;
  familia_id?: number | null;
  id: number;
  created_at: string;
}

export interface CausaSearchResponse {
  results: CausaRead[];
  total: number;
}

export interface CausaSingleResponse {
  result: CausaRead;
}

export interface CausaUpdate {
  nombre?: string | null;
  familia_id?: number | null;
}

export interface CentroDeServicioCreate {
  empresa_id?: number | null;
  codigo: string;
  nombre: string;
  slug: string;
  direccion?: string | null;
  telefono?: string | null;
  correo?: string | null;
  email?: string | null;
  numero_bodega?: string | null;
  id_numerico?: number | null;
  es_central: boolean;
  activo: boolean;
  responsable_id?: number | null;
}

export interface CentroDeServicioListResponse {
  results: CentroDeServicioRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface CentroDeServicioRead {
  empresa_id?: number | null;
  codigo: string;
  nombre: string;
  slug: string;
  direccion?: string | null;
  telefono?: string | null;
  correo?: string | null;
  email?: string | null;
  numero_bodega?: string | null;
  id_numerico?: number | null;
  es_central: boolean;
  activo: boolean;
  responsable_id?: number | null;
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export interface CentroDeServicioSingleResponse {
  result: CentroDeServicioRead;
}

export interface CentroDeServicioUpdate {
  empresa_id?: number | null;
  codigo?: string | null;
  nombre?: string | null;
  slug?: string | null;
  direccion?: string | null;
  telefono?: string | null;
  correo?: string | null;
  email?: string | null;
  numero_bodega?: string | null;
  id_numerico?: number | null;
  es_central?: boolean | null;
  activo?: boolean | null;
  responsable_id?: number | null;
}

export interface ClienteActualizadoInput {
  nombre?: string | null;
  nit?: string | null;
  telefono_principal?: string | null;
  telefono_secundario?: string | null;
  celular?: string | null;
  correo?: string | null;
  direccion?: string | null;
  pais?: string | null;
  departamento?: string | null;
  municipio?: string | null;
  nombre_facturacion?: string | null;
  direccion_envio?: string | null;
  origen?: string | null;
}

export interface ClienteAsesorCreate {
  cliente_id?: number | null;
  codigo_cliente?: string | null;
  nombre_asesor: string;
  telefono_asesor?: string | null;
  email_asesor?: string | null;
}

export interface ClienteAsesorListResponse {
  results: ClienteAsesorRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface ClienteAsesorRead {
  cliente_id?: number | null;
  codigo_cliente?: string | null;
  nombre_asesor: string;
  telefono_asesor?: string | null;
  email_asesor?: string | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface ClienteAsesorSingleResponse {
  result: ClienteAsesorRead;
}

export interface ClienteAsesorUpdate {
  cliente_id?: number | null;
  codigo_cliente?: string | null;
  nombre_asesor?: string | null;
  telefono_asesor?: string | null;
  email_asesor?: string | null;
}

export interface ClienteCreate {
  empresa_id?: number | null;
  codigo: string;
  nombre: string;
  nit?: string | null;
  telefono_principal?: string | null;
  telefono_secundario?: string | null;
  celular?: string | null;
  correo?: string | null;
  direccion?: string | null;
  pais?: string | null;
  departamento?: string | null;
  municipio?: string | null;
  nombre_facturacion?: string | null;
  direccion_envio?: string | null;
  origen?: string | null;
  codigo_sap?: string | null;
  activo?: boolean;
}

export interface ClienteListResponse {
  results: ClienteRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface ClienteNuevoInput {
  empresa_id?: number | null;
  codigo?: string | null;
  nombre: string;
  nit?: string | null;
  telefono_principal?: string | null;
  telefono_secundario?: string | null;
  celular?: string | null;
  correo?: string | null;
  direccion?: string | null;
  pais?: string | null;
  departamento?: string | null;
  municipio?: string | null;
  nombre_facturacion?: string | null;
  direccion_envio?: string | null;
  origen?: string | null;
}

export interface ClienteRead {
  empresa_id?: number | null;
  codigo: string;
  nombre: string;
  nit?: string | null;
  telefono_principal?: string | null;
  telefono_secundario?: string | null;
  celular?: string | null;
  correo?: string | null;
  direccion?: string | null;
  pais?: string | null;
  departamento?: string | null;
  municipio?: string | null;
  nombre_facturacion?: string | null;
  direccion_envio?: string | null;
  origen?: string | null;
  codigo_sap?: string | null;
  activo?: boolean;
  id: number;
  created_at: string;
  updated_at?: string | null;
  deleted_at?: string | null;
}

export interface ClienteSearchResponse {
  results: ClienteRead[];
}

export interface ClienteSingleResponse {
  result: ClienteRead;
}

export interface ClienteUpdate {
  nombre?: string | null;
  nit?: string | null;
  telefono_principal?: string | null;
  telefono_secundario?: string | null;
  celular?: string | null;
  correo?: string | null;
  direccion?: string | null;
  pais?: string | null;
  departamento?: string | null;
  municipio?: string | null;
  nombre_facturacion?: string | null;
  direccion_envio?: string | null;
  origen?: string | null;
  codigo_sap?: string | null;
  activo?: boolean | null;
}

export interface ConfiguracionWaterspiderCreate {
  centro_servicio_id: number;
  usuario_id?: number | null;
  activo?: boolean | null;
  horario_inicio?: string | null;
  horario_fin?: string | null;
  dias_semana?: number[] | null;
}

export interface ConfiguracionWaterspiderListResponse {
  results: ConfiguracionWaterspiderRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface ConfiguracionWaterspiderRead {
  centro_servicio_id: number;
  usuario_id?: number | null;
  activo?: boolean | null;
  horario_inicio?: string | null;
  horario_fin?: string | null;
  dias_semana?: number[] | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface ConfiguracionWaterspiderSingleResponse {
  result: ConfiguracionWaterspiderRead;
}

export interface ConfiguracionWaterspiderUpdate {
  usuario_id?: number | null;
  activo?: boolean | null;
  horario_inicio?: string | null;
  horario_fin?: string | null;
  dias_semana?: number[] | null;
}

export interface DiagnosticoCreateInput {
  recomendaciones?: string | null;
  es_reparable?: boolean | null;
  aplica_garantia?: boolean | null;
  tipo_resolucion?: TipoResolucion | null;
  estado?: EstadoDiagnostico;
  producto_alternativo_id?: number | null;
  descuento_porcentaje?: number | null;
  tipo_trabajo?: string | null;
  falla_ids?: number[];
  causa_ids?: number[];
  repuesto_ids?: number[];
}

export interface DiagnosticoListResponse {
  results: DiagnosticoRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface DiagnosticoRead {
  recomendaciones?: string | null;
  es_reparable?: boolean | null;
  aplica_garantia?: boolean | null;
  tipo_resolucion?: TipoResolucion | null;
  estado?: EstadoDiagnostico;
  producto_alternativo_id?: number | null;
  descuento_porcentaje?: number | null;
  tipo_trabajo?: string | null;
  id: number;
  incidente_id: number;
  tecnico_id: number;
  tecnico?: TecnicoNested | null;
  fallas?: FallaNested[];
  causas?: CausaNested[];
  repuestos?: RepuestoNested[];
  created_at: string;
  updated_at?: string | null;
}

export interface DiagnosticoSingleResponse {
  result: DiagnosticoRead;
}

export interface DireccionCreate {
  direccion: string;
  es_principal?: boolean;
}

export interface DireccionListResponse {
  results: DireccionRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface DireccionNuevaInput {
  direccion: string;
  es_principal?: boolean;
}

export interface DireccionRead {
  direccion: string;
  es_principal?: boolean;
  id: number;
  cliente_id: number;
  created_at: string;
  updated_at?: string | null;
  deleted_at?: string | null;
}

export interface DireccionSingleResponse {
  result: DireccionRead;
}

export interface DireccionUpdate {
  direccion?: string | null;
  es_principal?: boolean | null;
}

export interface EmpresaCreate {
  codigo: string;
  nombre: string;
  activo?: boolean;
}

export interface EmpresaListResponse {
  results: EmpresaRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface EmpresaRead {
  codigo: string;
  nombre: string;
  activo?: boolean;
  id: number;
  created_at: string;
}

export interface EmpresaSingleResponse {
  result: EmpresaRead;
}

export interface EmpresaUpdate {
  codigo?: string | null;
  nombre?: string | null;
  activo?: boolean | null;
}

export type EstadoDiagnostico = "PENDIENTE" | "EN_PROGRESO" | "COMPLETADO";

export type EstadoGuia = "PENDIENTE" | "CREADA" | "EN_TRANSITO" | "ENTREGADA" | "CANCELADA";

export type EstadoIncidente = "REGISTRADO" | "EN_DIAGNOSTICO" | "EN_REPARACION" | "ESPERA_REPUESTOS" | "ESPERA_APROBACION" | "REPARADO" | "EN_ENTREGA" | "ENTREGADO" | "CERRADO" | "CANCELADO" | "NOTA_DE_CREDITO" | "CAMBIO_POR_GARANTIA" | "RECHAZADO" | "COMPLETADO";

export interface FallaCreate {
  nombre: string;
  familia_id?: number | null;
}

export interface FallaListResponse {
  results: FallaRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface FallaNested {
  id: number;
  nombre: string;
}

export interface FallaRead {
  nombre: string;
  familia_id?: number | null;
  id: number;
  created_at: string;
}

export interface FallaSearchResponse {
  results: FallaRead[];
  total: number;
}

export interface FallaSingleResponse {
  result: FallaRead;
}

export interface FallaUpdate {
  nombre?: string | null;
  familia_id?: number | null;
}

export interface FamiliaProductoCreate {
  nombre: string;
  parent_id?: number | null;
}

export interface FamiliaProductoListResponse {
  results: FamiliaProductoRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface FamiliaProductoNested {
  id: number;
  nombre: string;
  parent_id?: number | null;
  created_at: string;
  updated_at?: string | null;
}

export interface FamiliaProductoRead {
  nombre: string;
  parent_id?: number | null;
  id: number;
  created_at: string;
}

export interface FamiliaProductoSingleResponse {
  result: FamiliaProductoRead;
}

export interface FamiliaProductoUpdate {
  nombre?: string | null;
  parent_id?: number | null;
}

export interface GruposColaFifoCreate {
  centro_servicio_id: number;
  nombre: string;
  orden: number;
  activo: boolean;
  color?: string | null;
  updated_by?: number | null;
}

export interface GruposColaFifoFamiliasCreate {
  grupo_id: number;
  familia_abuelo_id: number;
}

export interface GruposColaFifoFamiliasListResponse {
  results: GruposColaFifoFamiliasRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface GruposColaFifoFamiliasRead {
  grupo_id: number;
  familia_abuelo_id: number;
  id: number;
  created_at: string;
}

export interface GruposColaFifoFamiliasSingleResponse {
  result: GruposColaFifoFamiliasRead;
}

export interface GruposColaFifoListResponse {
  results: GruposColaFifoRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface GruposColaFifoRead {
  centro_servicio_id: number;
  nombre: string;
  orden: number;
  activo: boolean;
  color?: string | null;
  updated_by?: number | null;
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export interface GruposColaFifoSingleResponse {
  result: GruposColaFifoRead;
}

export interface GruposColaFifoUpdate {
  centro_servicio_id?: number | null;
  nombre?: string | null;
  orden?: number | null;
  activo?: boolean | null;
  color?: string | null;
  updated_by?: number | null;
}

export interface GuiaCreate {
  tipo: TipoGuia;
  estado: EstadoGuia;
  centro_de_servicio_origen_id: number;
  centro_de_servicio_destino_id?: number | null;
  incidente_id?: number | null;
  zigo_request_payload: Record<string, unknown>;
  zigo_guia_id?: string | null;
  zigo_guia_status?: string | null;
}

export interface GuiaListResponse {
  results: GuiaRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface GuiaRead {
  tipo: TipoGuia;
  estado: EstadoGuia;
  tracking_number?: string | null;
  zigo_guia_id?: string | null;
  zigo_guia_status?: string | null;
  numero_guia?: string | null;
  remitente?: string | null;
  direccion_remitente?: string | null;
  destinatario?: string | null;
  direccion_destinatario?: string | null;
  ciudad_destino?: string | null;
  cantidad_piezas?: number | null;
  peso?: number | null;
  tarifa?: number | null;
  referencia_1?: string | null;
  referencia_2?: string | null;
  recibido_por?: string | null;
  operador_pod?: string | null;
  telefono_destinatario?: string | null;
  empacador?: string | null;
  id: number;
  incidente_id?: number | null;
  centro_de_servicio_origen_id: number;
  centro_de_servicio_destino_id?: number | null;
  zigo_request_payload: Record<string, unknown>;
  zigo_response_data?: Record<string, unknown> | null;
  incidentes_codigos?: Record<string, unknown> | null;
  fecha_guia?: string | null;
  fecha_ingreso?: string | null;
  fecha_promesa_entrega?: string | null;
  fecha_entrega?: string | null;
  created_by?: number | null;
  created_at: string;
  updated_at?: string | null;
}

export interface GuiaSingleResponse {
  result: GuiaRead;
}

export interface GuiaUpdate {
  estado?: EstadoGuia | null;
  zigo_response_data?: Record<string, unknown> | null;
  tracking_number?: string | null;
  zigo_guia_id?: string | null;
  zigo_guia_status?: string | null;
  numero_guia?: string | null;
  fecha_guia?: string | null;
  fecha_ingreso?: string | null;
  fecha_promesa_entrega?: string | null;
  fecha_entrega?: string | null;
  remitente?: string | null;
  direccion_remitente?: string | null;
  destinatario?: string | null;
  direccion_destinatario?: string | null;
  ciudad_destino?: string | null;
  cantidad_piezas?: number | null;
  peso?: number | null;
  tarifa?: number | null;
  referencia_1?: string | null;
  referencia_2?: string | null;
  recibido_por?: string | null;
  operador_pod?: string | null;
  incidentes_codigos?: Record<string, unknown> | null;
  telefono_destinatario?: string | null;
  empacador?: string | null;
}

export interface IncidenteCambiarEstadoInput {
  nuevo_estado: EstadoIncidente;
}

export interface IncidenteCreate {
  producto_id?: number | null;
  tipologia: TipoIncidente;
  descripcion_problema?: string | null;
  centro_de_servicio_id: number;
  cliente_id?: number | null;
  propietario_id?: number | null;
  incidente_origen_id?: number | null;
  quiere_envio?: boolean;
  observaciones?: string | null;
  accesorios?: number[] | null;
  aplica_garantia?: boolean;
  tipo_resolucion?: TipoResolucion | null;
  direccion_envio_id?: number | null;
  cliente_nuevo?: unknown | null;
  cliente_actualizado?: unknown | null;
  direccion_nueva?: unknown | null;
  propietario_deja_maquina?: string | null;
  dpi_propietario_deja?: string | null;
  media?: unknown[] | null;
  es_reingreso?: boolean | null;
}

export interface IncidenteListResponse {
  results: IncidenteRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface IncidenteParticipacionListResponse {
  results: IncidenteParticipacionRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface IncidenteParticipacionRead {
  id: number;
  incidente_id: number;
  usuario_id: number;
  usuario?: UsuarioNested | null;
  tipo_participacion: TipoParticipacion;
  observaciones?: string | null;
  created_at?: string | null;
}

export interface IncidenteRead {
  id: number;
  empresa_id?: number | null;
  codigo: string;
  estado: EstadoIncidente;
  tipologia: TipoIncidente;
  descripcion_problema?: string | null;
  observaciones?: string | null;
  centro_de_servicio_id: number;
  cliente_id: number;
  propietario_id?: number | null;
  producto_id?: number | null;
  direccion_entrega_id?: number | null;
  tracking_token: string;
  incidente_origen_id?: number | null;
  quiere_envio: boolean;
  aplica_garantia?: boolean | null;
  tipo_resolucion?: TipoResolucion | null;
  fecha_ingreso?: string | null;
  fecha_entrega?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface IncidenteSingleResponse {
  result: IncidenteRead;
}

export interface IncidenteUpdate {
  producto_id?: number | null;
  tipologia?: TipoIncidente | null;
  descripcion_problema?: string | null;
  centro_de_servicio_id?: number | null;
  cliente_id?: number | null;
  propietario_id?: number | null;
  incidente_origen_id?: number | null;
  quiere_envio?: boolean | null;
  observaciones?: string | null;
  accesorios?: number[] | null;
  aplica_garantia?: boolean | null;
  tipo_resolucion?: TipoResolucion | null;
}

export interface IngresoCompletoInput {
  tipologia: TipoIncidente;
  centro_de_servicio_id: number;
  producto_id?: number | null;
  descripcion_problema?: string | null;
  observaciones?: string | null;
  quiere_envio?: boolean;
  aplica_garantia?: boolean;
  tipo_resolucion?: TipoResolucion | null;
  cliente_id?: number | null;
  propietario_id?: number | null;
  incidente_origen_id?: number | null;
  direccion_envio_id?: number | null;
  cliente_nuevo?: ClienteNuevoInput | null;
  cliente_actualizado?: ClienteActualizadoInput | null;
  direccion_nueva?: DireccionNuevaInput | null;
  propietario_deja_maquina?: string | null;
  dpi_propietario_deja?: string | null;
  accesorios?: number[] | null;
  media?: MediaInput[] | null;
  es_reingreso?: boolean | null;
}

export interface InventarioCreate {
  centro_servicio_id: number;
  codigo_repuesto: string;
  ubicacion_legacy?: string;
  descripcion?: string | null;
  cantidad?: number;
  costo_unitario?: number | null;
  bodega?: string | null;
  ubicacion_id?: number | null;
  bodega_id?: number | null;
}

export interface InventarioRead {
  centro_servicio_id: number;
  codigo_repuesto: string;
  ubicacion_legacy?: string;
  descripcion?: string | null;
  cantidad?: number;
  costo_unitario?: number | null;
  bodega?: string | null;
  ubicacion_id?: number | null;
  bodega_id?: number | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface InventarioRepuestoCreate {
  nombre: string;
  descripcion?: string | null;
  codigo: string;
  clave?: string | null;
  centro_de_servicio_id: number;
  ubicacion: string;
  cantidad: number;
  costo_unitario: number;
}

export interface InventarioRepuestoListResponse {
  results: InventarioRepuestoRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface InventarioRepuestoRead {
  nombre: string;
  descripcion?: string | null;
  codigo: string;
  clave?: string | null;
  centro_de_servicio_id: number;
  ubicacion: string;
  cantidad: number;
  costo_unitario: number;
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export interface InventarioRepuestoSingleResponse {
  result: InventarioRepuestoRead;
}

export interface InventarioRepuestoUpdate {
  nombre?: string | null;
  descripcion?: string | null;
  codigo?: string | null;
  clave?: string | null;
  centro_de_servicio_id?: number | null;
  ubicacion?: string | null;
  cantidad?: number | null;
  costo_unitario?: number | null;
}

export interface InventarioUpdate {
  centro_servicio_id?: number | null;
  codigo_repuesto?: string | null;
  ubicacion_legacy?: string | null;
  descripcion?: string | null;
  cantidad?: number | null;
  costo_unitario?: number | null;
  bodega?: string | null;
  ubicacion_id?: number | null;
  bodega_id?: number | null;
}

export interface ListadoAbastecimientoPickingLogCreate {
  item_id: number;
  picker_id: number;
  cantidad_pickeada: number;
  observaciones?: string | null;
}

export interface ListadoAbastecimientoPickingLogListResponse {
  results: ListadoAbastecimientoPickingLogRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface ListadoAbastecimientoPickingLogRead {
  item_id: number;
  picker_id: number;
  cantidad_pickeada: number;
  observaciones?: string | null;
  id: number;
  fecha_picking?: string | null;
}

export interface ListadoAbastecimientoPickingLogSingleResponse {
  result: ListadoAbastecimientoPickingLogRead;
}

export interface ListadoAbastecimientoPickingLogUpdate {
  cantidad_pickeada?: number | null;
  observaciones?: string | null;
}

export interface LoginRequestSchema {
  email: string;
  password: string;
}

export interface MediaInput {
  url: string;
  tipo?: string | null;
  visibilidad?: string | null;
  descripcion?: string | null;
}

export interface MovimientoInventarioCreate {
  centro_servicio_id: number;
  repuesto_id: number;
  tipo_movimiento: TipoMovimientoInventario;
  cantidad: number;
  stock_anterior: number;
  stock_nuevo: number;
  ubicacion?: string | null;
  referencia?: string | null;
  motivo?: string | null;
  created_by_id?: number | null;
}

export interface MovimientoInventarioListResponse {
  results: MovimientoInventarioRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface MovimientoInventarioRead {
  centro_servicio_id: number;
  repuesto_id: number;
  tipo_movimiento: TipoMovimientoInventario;
  cantidad: number;
  stock_anterior: number;
  stock_nuevo: number;
  ubicacion?: string | null;
  referencia?: string | null;
  motivo?: string | null;
  created_by_id?: number | null;
  id: number;
  created_at?: string | null;
}

export interface MovimientoInventarioSingleResponse {
  result: MovimientoInventarioRead;
}

export interface NotificacionRead {
  id: number;
  incidente_id: number;
  tipo: string;
  destinatario: string;
  mensaje: string;
  enviada: boolean;
  created_at?: string | null;
}

export interface PaginaCreate {
  proyecto: string;
  modulo: string;
  nombre: string;
  ruta: string;
  descripcion?: string | null;
  icono?: string | null;
  orden?: number;
  activo?: boolean;
}

export interface PaginaListResponse {
  results: PaginaRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface PaginaRead {
  proyecto: string;
  modulo: string;
  nombre: string;
  ruta: string;
  descripcion?: string | null;
  icono?: string | null;
  orden?: number;
  activo?: boolean;
  id: number;
  created_at: string;
}

export interface PaginaSingleResponse {
  result: PaginaRead;
}

export interface PaginaUpdate {
  proyecto?: string | null;
  modulo?: string | null;
  nombre?: string | null;
  ruta?: string | null;
  descripcion?: string | null;
  icono?: string | null;
  orden?: number | null;
  activo?: boolean | null;
}

export interface PreguntaAuditoriaCreate {
  pregunta: string;
  seccion: string;
  activo?: boolean;
}

export interface PreguntaAuditoriaListResponse {
  results: PreguntaAuditoriaRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface PreguntaAuditoriaRead {
  pregunta: string;
  seccion: string;
  activo?: boolean;
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export interface PreguntaAuditoriaSingleResponse {
  result: PreguntaAuditoriaRead;
}

export interface PreguntaAuditoriaUpdate {
  pregunta?: string | null;
  seccion?: string | null;
  activo?: boolean | null;
}

export interface ProductoCreate {
  codigo: string;
  sku?: string | null;
  marca?: string | null;
  modelo?: string | null;
  descripcion?: string | null;
  activo?: boolean;
  clave?: string | null;
  descontinuado?: boolean;
  es_sugerido?: boolean;
  url_foto?: string | null;
  familia_padre_id?: number | null;
  familia_abuelo_id?: number | null;
  unidades_disponibles?: number | null;
  precio_minimo?: number | string | null;
  precio_cliente?: number | string | null;
  precio_con_descuento?: number | string | null;
}

export interface ProductoListResponse {
  results: ProductoRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface ProductoRead {
  codigo: string;
  sku?: string | null;
  marca?: string | null;
  modelo?: string | null;
  descripcion?: string | null;
  activo?: boolean;
  clave?: string | null;
  descontinuado?: boolean;
  es_sugerido?: boolean;
  url_foto?: string | null;
  familia_padre_id?: number | null;
  familia_abuelo_id?: number | null;
  unidades_disponibles?: number | null;
  precio_minimo?: string | null;
  precio_cliente?: string | null;
  precio_con_descuento?: string | null;
  id: number;
  created_at: string;
  updated_at?: string | null;
  familias?: FamiliaProductoNested[];
}

export interface ProductoSearchResponse {
  results: ProductoRead[];
}

export interface ProductoSingleResponse {
  result: ProductoRead;
}

export interface ProductoUpdate {
  codigo?: string | null;
  sku?: string | null;
  marca?: string | null;
  modelo?: string | null;
  descripcion?: string | null;
  activo?: boolean | null;
  clave?: string | null;
  descontinuado?: boolean | null;
  es_sugerido?: boolean | null;
  url_foto?: string | null;
  familia_padre_id?: number | null;
  familia_abuelo_id?: number | null;
  unidades_disponibles?: number | null;
  precio_minimo?: number | string | null;
  precio_cliente?: number | string | null;
  precio_con_descuento?: number | string | null;
}

export interface RefreshTokenRequest {
  refresh_token: string;
}

export interface RepuestoCreate {
  codigo: string;
  familia_id?: number | null;
  clave?: string | null;
  descripcion?: string | null;
  url_foto?: string | null;
  codigo_producto?: string | null;
  disponible_mostrador?: boolean;
  es_catalogo_truper?: boolean;
  codigo_padre?: string | null;
  prefijo_clasificacion?: string | null;
  es_codigo_padre?: boolean;
}

export interface RepuestoListResponse {
  results: RepuestoRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface RepuestoNested {
  id: number;
  codigo: string;
  descripcion?: string | null;
}

export interface RepuestoRead {
  codigo: string;
  familia_id?: number | null;
  clave?: string | null;
  descripcion?: string | null;
  url_foto?: string | null;
  codigo_producto?: string | null;
  disponible_mostrador?: boolean;
  es_catalogo_truper?: boolean;
  codigo_padre?: string | null;
  prefijo_clasificacion?: string | null;
  es_codigo_padre?: boolean;
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export interface RepuestoSingleResponse {
  result: RepuestoRead;
}

export interface RepuestoUpdate {
  codigo?: string | null;
  familia_id?: number | null;
  clave?: string | null;
  descripcion?: string | null;
  url_foto?: string | null;
  codigo_producto?: string | null;
  disponible_mostrador?: boolean | null;
  es_catalogo_truper?: boolean | null;
  codigo_padre?: string | null;
  prefijo_clasificacion?: string | null;
  es_codigo_padre?: boolean | null;
}

export interface RolListResponse {
  results: RolRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface RolPaginaCreate {
  rol_id: number;
  pagina_id: number;
  puede_ver?: boolean | null;
  updated_by?: number | null;
}

export interface RolPaginaListResponse {
  results: RolPaginaRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface RolPaginaRead {
  rol_id: number;
  pagina_id: number;
  puede_ver?: boolean | null;
  updated_by?: number | null;
  id: number;
  created_at?: string | null;
}

export interface RolPaginaSingleResponse {
  result: RolPaginaRead;
}

export interface RolPaginaUpdate {
  puede_ver?: boolean | null;
  updated_by?: number | null;
}

export interface RolRead {
  nombre: string;
  slug: string;
  descripcion?: string | null;
  id: number;
}

export interface RolSchema {
  id: number;
  nombre: string;
  slug: string;
  descripcion?: string | null;
}

export interface TecnicoNested {
  id: number;
  nombre: string;
  apellido?: string | null;
  email?: string | null;
}

export type TipoGuia = "RECOLECTA" | "TRASLADO" | "ENTREGA";

export type TipoIncidente = "MANTENIMIENTO" | "REPARACION";

export type TipoMovimientoInventario = "ENTRADA" | "SALIDA" | "AJUSTE";

export type TipoParticipacion = "REGISTRADO_POR" | "DIAGNOSTICADO_POR" | "REPARADO_POR" | "APROBADO_GARANTIA_POR" | "SUPERVISADO_POR" | "SUSTITUIDO_POR" | "ENTREGADO_POR" | "TECNICO_ASIGNADO" | "DIAGNOSTICO_REGISTRADO";

export type TipoResolucion = "REPARAR_EN_GARANTIA" | "PRESUPUESTO" | "CANJE" | "NOTA_DE_CREDITO";

export interface TokenResponseSchema {
  access_token: string;
  refresh_token: string;
  token_type?: string;
  expires_in: number;
  user: UsuarioSchema;
}

export interface UbicacionCreate {
  bodega_id?: number | null;
  codigo?: string | null;
  pasillo?: string | null;
  rack?: string | null;
  nivel?: string | null;
  caja?: string | null;
  activo: boolean;
}

export interface UbicacionListResponse {
  results: UbicacionRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface UbicacionRead {
  bodega_id?: number | null;
  codigo?: string | null;
  pasillo?: string | null;
  rack?: string | null;
  nivel?: string | null;
  caja?: string | null;
  activo: boolean;
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export interface UbicacionSingleResponse {
  result: UbicacionRead;
}

export interface UbicacionUpdate {
  bodega_id?: number | null;
  codigo?: string | null;
  pasillo?: string | null;
  rack?: string | null;
  nivel?: string | null;
  caja?: string | null;
  activo?: boolean | null;
}

export interface UsuarioCreateSchema {
  email: string;
  nombre: string;
  apellido?: string | null;
  telefono?: string | null;
  activo?: boolean;
  codigo_empleado?: string | null;
  cliente_id?: number | null;
  password: string;
  roles: string[];
}

export interface UsuarioNested {
  id: number;
  nombre: string;
  apellido?: string | null;
  email?: string | null;
}

export interface UsuarioReadWithRoles {
  id: number;
  nombre: string;
  apellido?: string | null;
  email: string;
  telefono?: string | null;
  activo?: boolean;
  codigo_empleado?: string | null;
  empresa_id?: number | null;
  centro_de_servicio_id?: number | null;
  cliente_id?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
  deleted_at?: string | null;
  roles?: RolRead[];
}

export interface UsuarioSchema {
  email: string;
  nombre: string;
  apellido?: string | null;
  telefono?: string | null;
  activo?: boolean;
  codigo_empleado?: string | null;
  cliente_id?: number | null;
  id: number;
  roles?: RolSchema[];
  centro_de_servicio?: CentroDeServicioRead | null;
}

export interface VerificacionReincidenciaCreate {
  incidente_id: number;
  razon: string;
  verificado?: boolean;
}

export interface VerificacionReincidenciaListResponse {
  results: VerificacionReincidenciaRead[];
  total: number;
  skip: number;
  limit: number;
}

export interface VerificacionReincidenciaRead {
  incidente_id: number;
  razon: string;
  verificado?: boolean;
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export interface VerificacionReincidenciaSingleResponse {
  result: VerificacionReincidenciaRead;
}

export interface VerificacionReincidenciaUpdate {
  incidente_id?: number | null;
  razon?: string | null;
  verificado?: boolean | null;
}
