-- Crear tabla CDS_Fallas
CREATE TABLE public."CDS_Fallas" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  familia_id bigint REFERENCES public."CDS_Familias"(id) ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Crear tabla CDS_Causas
CREATE TABLE public."CDS_Causas" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  familia_id bigint REFERENCES public."CDS_Familias"(id) ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public."CDS_Fallas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."CDS_Causas" ENABLE ROW LEVEL SECURITY;

-- Políticas para CDS_Fallas
CREATE POLICY "Admin puede gestionar fallas"
ON public."CDS_Fallas"
FOR ALL
USING (has_role(auth.uid(), 'admin'))
WITH CHECK (has_role(auth.uid(), 'admin'));

CREATE POLICY "Usuarios autenticados pueden ver fallas"
ON public."CDS_Fallas"
FOR SELECT
USING (auth.uid() IS NOT NULL);

-- Políticas para CDS_Causas
CREATE POLICY "Admin puede gestionar causas"
ON public."CDS_Causas"
FOR ALL
USING (has_role(auth.uid(), 'admin'))
WITH CHECK (has_role(auth.uid(), 'admin'));

CREATE POLICY "Usuarios autenticados pueden ver causas"
ON public."CDS_Causas"
FOR SELECT
USING (auth.uid() IS NOT NULL);

-- Índices para mejorar búsquedas
CREATE INDEX idx_fallas_familia ON public."CDS_Fallas"(familia_id);
CREATE INDEX idx_causas_familia ON public."CDS_Causas"(familia_id);
CREATE INDEX idx_fallas_nombre ON public."CDS_Fallas"(nombre);
CREATE INDEX idx_causas_nombre ON public."CDS_Causas"(nombre);