-- Insertar nuevos productos Truper
INSERT INTO productos (codigo, clave, descripcion, url_foto, familia_producto, descontinuado) VALUES
('12909', 'LAGAS-3300', 'HIDROLAVADORA CON MOTOR A GASOLINA, 3,300 PSI, TRUPER', 'https://www.truper.com/media/import/imagenes/LAGAS-3300.jpg', 'Hidrolavadoras', false),
('12908', 'LAGAS-2800', 'HIDROLAVADORA CON MOTOR A GASOLINA, 2,800 PSI, TRUPER', 'https://www.truper.com/media/import/imagenes/LAGAS-2800.jpg', 'Hidrolavadoras', false),
('12671', 'DES-63', 'DESMALEZADORA A GASOLINA 63 CC MANGO "BICI", 17" CORTE', 'https://www.truper.com/media/import/imagenes/DES-63.jpg', 'Electricas', false),
('14013', 'ESMA-4-1/2A12', 'ESMERILADORA ANGULAR 4-1/2" 700 W, PROFESIONAL, TRUPER', 'https://www.truper.com/media/import/imagenes/ESMA-4-1-2A12.jpg', 'Electricas', false),
('16683', 'ESMA-4-1/2A9', 'ESMERILADORA ANGULAR 4-1/2" 800 W, PROFESIONAL, TRUPER', 'https://www.truper.com/media/import/imagenes/ESMA-4-1-2A9.jpg', 'Electricas', false),
('15007', 'COMP-50LT', 'COMPRESOR HORIZONTAL 50L, 3-1/2 HP (POTENCIA MÁXIMA),127 V', 'https://www.truper.com/media/import/imagenes/COMP-50LT.jpg', 'Compresores', false),
('12873', 'ESMA-4512N', 'ESMERILADORA ANGULAR 4-1/2" 1250 W, INDUSTRIAL, TRUPER', 'https://www.truper.com/media/import/imagenes/ESMA-4512N.jpg', 'Electricas', false),
('11032', 'DES-520', 'DESMALEZADORA A GASOLINA 52 CC MANGO "BICI", 18" CORTE', 'https://www.truper.com/media/import/imagenes/DES-520.jpg', '2 Tiempos', false),
('19323', 'ROEL-60N', 'ROTOMARTILLO SDS PLUS 6 JOULES 1600 W, INDUSTRIAL, TRUPER', 'https://www.truper.com/media/import/imagenes/ROEL-60N.jpg', 'Electricas', false),
('12496', 'DES-26C', 'DESBROZADORA A GASOLINA 26 CC MANGO "D", 17" DE CORTE', 'https://www.truper.com/media/import/imagenes/DES-26C.jpg', '2 Tiempos', false),
('12872', 'ESMA-4590N', 'ESMERILADORA ANGULAR 4-1/2" 950 W, INDUSTRIAL, TRUPER', 'https://www.truper.com/media/import/imagenes/ESMA-4590N.jpg', 'Electricas', false),
('12498', 'DES-30C', 'DESBROZADORA A GASOLINA 30 CC MANGO "D", 17" CORTE, CURVA', 'https://www.truper.com/media/import/imagenes/DES-30C.jpg', '2 Tiempos', false),
('18156', 'ERGO-4580', 'ESMERILADORA ANGULAR 4-1/2" 850 W, ERGO-PRO, TRUPER', 'https://www.truper.com/media/import/imagenes/ERGO-4580.jpg', 'Electricas', false),
('101595', 'HILA-2000', 'HIDROLAVADORA ELÉCTRICA 2000 PSI, TRUPER', 'http://truper.com/media/import/imagenes/HILA-2000.jpg', 'Hidrolavadoras', false),
('15003', 'BOS-1LPX', 'BOMBA SUMERGIBLE METÁLICA PARA AGUA LIMPIA USO RUDO 1 HP', 'https://www.truper.com/media/import/imagenes/BOS-1LPX.jpg', 'Hidraulicas', false),
('11029', 'DES-330', 'DESMALEZADORA A GASOLINA 33 CC MANGO "BICI", 18" CORTE', 'https://www.truper.com/media/import/imagenes/DES-330.jpg', '2 Tiempos', false),
('11031', 'DES-430', 'DESMALEZADORA A GASOLINA 43 CC MANGO "BICI", 18" CORTE', 'https://www.truper.com/media/import/imagenes/DES-430.jpg', '2 Tiempos', false),
('15656', 'COMP-80LV', 'COMPRESOR VERTICAL, 80 L, 3-1/2 HP (POTENCIA MÁXIMA ), 127V', 'https://www.truper.com/media/import/imagenes/COMP-80LV.jpg', 'Compresores', false),
('19360', 'COMP-50LV', 'COMPRESOR VERTICAL, 50 L, 3-1/2 HP (POTENCIA MÁXIMA ), 127V', 'https://www.truper.com/media/import/imagenes/COMP-50LV.jpg', 'Compresores', false),
('10068', 'BOAP-1/2', 'BOMBA PERIFÉRICA 1/2 HP, TRUPER EXPERT', 'https://www.truper.com/media/import/imagenes/BOAP-1-2.jpg', 'Hidraulicas', false),
('101594', 'HILA-1800', 'HIDROLAVADORA ELÉCTRICA 1800 PSI, TRUPER', 'https://www.truper.com/media/import/imagenes/HILA-1800.jpg', 'Hidrolavadoras', false),
('26034', 'GEN-25P', 'GENERADOR ELÉCTRICO CON MOTOR A GASOLINA, 2.8 KW, PRETUL', 'https://www.truper.com/media/import/imagenes/GEN-25P.jpg', 'Estacionarias', false),
('17116', 'MOTB-2', 'MOTOBOMBA AUTOCEBANTE 2" X 2" A GASOLINA 7 HP, TRUPER', 'https://www.truper.com/media/import/imagenes/MOTB-2.jpg', 'Hidraulicas', false),
('26033', 'GEN-10P', 'GENERADOR ELÉCTRICO CON MOTOR A GASOLINA, 1.1 KW, PRETUL', 'https://www.truper.com/media/import/imagenes/GEN-10P.jpg', 'Estacionarias', false),
('15345', 'GEN-80X', 'GENERADOR ELÉCTRICO PORTÁTIL 8 KW MOTOR A GASOLINA, TRUPER', 'https://www.truper.com/media/import/imagenes/GEN-80X.jpg', 'Estacionarias', false),
('101263', 'DES-550', 'DESBROZADORA ELÉCTRICA 550 W MANGO "D", 13" CORTE, TRUPER', 'https://www.truper.com/media/import/imagenes/DES-550.jpg', 'Electricas', false),
('15006', 'COMP-25LT', 'COMPRESOR HORIZONTAL 25L, 3 HP (POTENCIA MÁXIMA), 127 V', 'https://www.truper.com/media/import/imagenes/COMP-25LT.jpg', 'Compresores', false),
('100893', 'MADE-20NX', 'MARTILLO DEMOLEDOR HEX 20 KG 55 J 1600 W, TRUPER EXPERT', 'https://www.truper.com/media/import/imagenes/MADE-20NX.jpg', 'Electricas', false),
('14659', 'ROTO-1/2A9', 'ROTOMARTILLO 1/2" 850 W, PROFESIONAL, TRUPER', 'https://www.truper.com/media/import/imagenes/ROTO-1-2A9.jpg', 'Electricas', false),
('19968', 'P-622', 'PODADORA CON MOTOR A GASOLINA DE 6 HP, 22" DE CORTE, TRUPER', 'https://www.truper.com/media/import/imagenes/P-622.jpg', 'Estacionarias', false),
('19366', 'COMP-240LV', 'COMPRESOR VERTICAL 240 L, 4 HP (POTENCIA MÁXIMA ), 220 V', 'https://www.truper.com/media/import/imagenes/COMP-240LV.jpg', 'Compresores', false),
('22430', 'DES-25P', 'DESBROZADORA A GASOLINA 25 CC MANGO "D", 17" CORTE PRETUL', 'https://www.truper.com/media/import/imagenes/DES-25P.jpg', '2 Tiempos', false),
('27045', 'MOT-6020P', 'MOTOSIERRA 60 CC A GASOLINA CON BARRA DE 20", PRETUL', 'https://www.truper.com/media/import/imagenes/MOT-6020P.jpg', '2 Tiempos', false),
('13180', 'CLNE-18', 'CLAVADORA NEUMÁTICA PROFESIONAL, CALIBRE 18, TRUPER', 'https://www.truper.com/media/import/imagenes/CLNE-18.jpg', 'Neumaticas', false),
('29961', 'SOIN-101MP', 'MINI SOLDADORA INVERSORA 100 A, 127 V, PRETUL', 'https://www.truper.com/media/import/imagenes/SOIN-101MP.jpg', 'Estacionarias', false),
('10070', 'BOAP-1', 'BOMBA PERIFÉRICA 1 HP, TRUPER EXPERT', 'https://www.truper.com/media/import/imagenes/BOAP-1.jpg', 'Hidraulicas', false),
('16053', 'SOIN-130/200', 'SOLDADORA INVERSORA BI-VOLTAJE 200 A, 127 V/220 V, TRUPER', 'https://www.truper.com/media/import/imagenes/SOIN-130-200.jpg', 'Estacionarias', false),
('18154', 'TALI-20A', 'TALADRO INALÁMBRICO 1/2" 20 V, PROFESIONAL, TRUPER', 'https://www.truper.com/media/import/imagenes/TALI-20A.jpg', 'Electricas', false),
('24035', 'ESMA-4-1/2P2', 'ESMERILADORA ANGULAR 4-1/2" 700 W, PRETUL', 'https://www.truper.com/media/import/imagenes/ESMA-4-1-2P2.jpg', 'Electricas', false),
('12114', 'BOAP-1A2', 'BOMBA PERIFÉRICA 1 HP, TRUPER', 'https://www.truper.com/media/import/imagenes/BOAP-1A2.jpg', 'Hidraulicas', false),
('15342', 'GEN-25X', 'GENERADOR ELÉCTRICO PORTÁTIL 2.5 KW MOTOR A GASOLINA, TRUPER', 'https://www.truper.com/media/import/imagenes/GEN-25X.jpg', 'Estacionarias', false),
('14658', 'ROTO-1/2A8', 'ROTOMARTILLO 1/2" 750 W, PROFESIONAL, TRUPER', 'https://www.truper.com/media/import/imagenes/ROTO-1-2A8.jpg', 'Electricas', false),
('19011', 'COMP-50L', 'COMPRESOR 50LTS 2.5HP LUBRICADO', 'https://www.truper.com/media/import/imagenes/COMP-50L.jpg', 'Compresores', true)
ON CONFLICT (codigo) DO NOTHING;