// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://pozycdicivabmptgpmcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvenljZGljaXZhYm1wdGdwbWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4NjEwOTYsImV4cCI6MjA4NDQzNzA5Nn0.UhpSW6ut4VH0A6c8iKbs_UwgVDVScfr2L8og_JKrDaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
